name: Notify Discord on Release

on:
  release:
    types: [published]

jobs:
  notify-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code (master)
        uses: actions/checkout@v3
        with:
          ref: master  # Щоб взяти version.txt з master

      - name: Read version from version.txt
        id: version
        run: |
          RAW_VERSION=$(head -n 1 version.txt | sed 's/%/%25/g; s/\n/%0A/g; s/\r/%0D/g; s/|/%7C/g')
          echo "VERSION=$RAW_VERSION" >> $GITHUB_OUTPUT

      - name: Send Discord Notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.USFDISCORDHOOK }}
          RELEASE_NAME: ${{ github.event.release.name }}
          RELEASE_BODY: ${{ github.event.release.body }}
          RELEASE_URL: ${{ github.event.release.html_url }}
          RELEASE_TAG: ${{ github.event.release.tag_name }}
          VERSION_FROM_FILE: ${{ steps.version.outputs.VERSION }}
          IMAGE_URL: https://raw.githubusercontent.com/AlexLiberty/StarCitizen_VoicePack_Updater_Releases/refs/heads/main/assets/IMG_7075.jpeg
        run: |
          EMBED=$(jq -n \
            --arg title "🚀 Новий реліз: $RELEASE_NAME" \
            --arg description "$RELEASE_BODY" \
            --arg url "$RELEASE_URL" \
            --arg version "GitHub tag: $RELEASE_TAG\n#version=${VERSION_FROM_FILE}" \
            --arg image "$IMAGE_URL" \
            --argjson color 5814783 \
            '{embeds: [{title: $title, description: ($version + "\n\n" + $description), url: $url, color: $color, image: {url: $image}}]}' )

          curl -X POST -H "Content-Type: application/json" \
            -d "$EMBED" \
            "$DISCORD_WEBHOOK"
